spring:
  datasource:
    url: jdbc:postgresql://localhost:19043/jwtauth2
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #        use_sql_comments: true
        type:
          - hibernate.type: true
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

#logging:
#  level:
#    org:
#      postgresql: info
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace


security:
  jwt:
    access-token-secret-key: ${JWT_ACCESS_SECRET}
  api:
    shop: ${API_SHOP_URL}
    admin: ${API_ADMIN_URL}
