spring:
  application:
    name: EcommerceBackendNashTech
  datasource:
    url: jdbc:postgresql://localhost:19043/jwtauth2
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: postgresql
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
logging:
  level:
    org:
    #      postgresql: warn
    #      hibernate: error
#    org.springframework.security: warn
#    root: warn
#    web: warn


security:
  jwt:
    access-token-secret-key: ${JWT_ACCESS_SECRET}
    refresh-token-secret-key: ${JWT_REFRESH_SECRET}