spring:
  file:
    name: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #        use_sql_comments: true
        type:
          - hibernate.type: true
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
  main:
    banner-mode: off

logging:
  level:
    root: warn
    com.spring.ecommerce: warn
    org:
      postgresql: error
      hibernate:
        SQL: error
        type:
          descriptor:
            sql: error



security:
  jwt:
    access-token-secret-key: ${JWT_ACCESS_SECRET}
  api:
    shop: ${API_SHOP_URL}
    admin: ${API_ADMIN_URL}
